-- 외래키
CREATE TABLE daddy(
	idx 	number(10),
	mID		number(10) PRIMARY KEY 
);

CREATE TABLE daughter(
	idx		number(10) PRIMARY KEY ,
	mID		number(10),
	CONSTRAINTS fk_da FOREIGN KEY(mID)
	REFERENCES daddy(mID)  
);

INSERT INTO DADDY VALUES (1, 10);
INSERT INTO DADDY VALUES (2, 20);
SELECT * FROM DADDY d ;

INSERT INTO DAUGHTER VALUES (100, 10);
INSERT INTO DAUGHTER VALUES (101, 10);
INSERT INTO DAUGHTER VALUES (102, 10);
INSERT INTO DAUGHTER VALUES (200, 10);
INSERT INTO DAUGHTER VALUES (201, 20);
INSERT INTO DAUGHTER VALUES (300, 30);
DELETE FROM DAUGHTER d2 WHERE IDX = 100;
DELETE FROM DAUGHTER d2 WHERE MID = 10;
DELETE FROM DAUGHTER;
DELETE FROM DADDY d ;
DELETE FROM DADDY d2 WHERE IDX = 1;
DROP TABLE DADDY ;
DROP TABLE DAUGHTER ;
SELECT * FROM DAUGHTER d ;


DELETE FROM DAUGHTER d2 WHERE MID = 10;
DELETE FROM DADDY d2 WHERE IDX = 1;

-------------------------------------------------------------------------
----- ON DELETE CASCADE
CREATE TABLE daddy(
	idx 	number(10),
	mID		number(10) PRIMARY KEY 
);

CREATE TABLE daughter(
	idx		number(10) PRIMARY KEY ,
	mID		number(10),
	CONSTRAINTS fk_da FOREIGN KEY(mID)
	REFERENCES daddy(mID) ON DELETE CASCADE
);

INSERT INTO DADDY VALUES (1, 10);
INSERT INTO DADDY VALUES (2, 20);
SELECT * FROM DADDY d ;

INSERT INTO DAUGHTER VALUES (100, 10);
INSERT INTO DAUGHTER VALUES (101, 10);
INSERT INTO DAUGHTER VALUES (102, 10);
INSERT INTO DAUGHTER VALUES (200, 10);
INSERT INTO DAUGHTER VALUES (201, 20);
SELECT * FROM DAUGHTER d ;

DELETE FROM DADDY d2 WHERE IDX = 2;
DROP TABLE DAUGHTER ;
DROP TABLE daddy ;

--------------------------------------------------------------
-- ON DELETE SET NULL
CREATE TABLE daddy(
	idx 	number(10),
	mID		number(10) PRIMARY KEY 
);

CREATE TABLE daughter(
	idx		number(10) PRIMARY KEY ,
	mID		number(10),
	CONSTRAINTS fk_da FOREIGN KEY(mID)
	REFERENCES daddy(mID) ON DELETE SET NULL
);

-- Alt + x
INSERT INTO DADDY VALUES (1, 10);
INSERT INTO DADDY VALUES (2, 20);
SELECT * FROM DADDY d ;

INSERT INTO DAUGHTER VALUES (100, 10);
INSERT INTO DAUGHTER VALUES (101, 10);
INSERT INTO DAUGHTER VALUES (102, 10);
INSERT INTO DAUGHTER VALUES (200, 10);
INSERT INTO DAUGHTER VALUES (201, 20);
SELECT * FROM DAUGHTER d ;

DELETE FROM DADDY d2 WHERE IDX = 1;

--------------------------------------------------------------------------
-- check

CREATE TABLE check_test(
	gender		varchar2(10)
		CONSTRAINTS check_gender CHECK (gender IN('M','F'))
);

INSERT INTO check_test VALUES('M');
INSERT INTO check_test VALUES('F');
INSERT INTO check_test VALUES('남자');
INSERT INTO check_test VALUES('여자');
SELECT * FROM check_test;