
-- inner join(EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS)
-- first_name, last_name, email, department_id, department_name,
-- job_id, job_title, city
-- city는 Seattle
-- 하나의 select 문
-- 원본 select
SELECT
	e.FIRST_NAME ,
	e.LAST_NAME ,
	e.EMAIL ,
	d.DEPARTMENT_ID ,
	d.DEPARTMENT_NAME 
	--j.JOB_ID ,
	--j.JOB_TITLE ,
	--l.CITY
FROM EMPLOYEES e
	inner join DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
	INNER JOIN JOBS j 
	ON e.JOB_ID = j.JOB_ID
	INNER JOIN LOCATIONS l 
	ON d.LOCATION_ID = l.LOCATION_ID
-- WHERE e.DEPARTMENT_ID = 130	
;

SELECT
	e.FIRST_NAME ,
	e.LAST_NAME ,
	e.EMAIL ,
	d.DEPARTMENT_ID ,
	d.DEPARTMENT_NAME 
	--j.JOB_ID ,
	--j.JOB_TITLE ,
	--l.CITY
FROM DEPARTMENTS d
	INNER JOIN LOCATIONS l 
	ON d.LOCATION_ID = l.LOCATION_ID
	inner join EMPLOYEES e 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
	INNER JOIN JOBS j 
	ON e.JOB_ID = j.JOB_ID
;

SELECT DISTINCT e.DEPARTMENT_ID 
FROM EMPLOYEES e
	inner join DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
;

SELECT 	d.DEPARTMENT_ID , l.LOCATION_ID 
FROM 	DEPARTMENTS d 
	INNER JOIN LOCATIONS l
	ON d.LOCATION_ID  = l.LOCATION_ID
;

-- EMPLOYEES 테이블과 DEPARTMENTS 테이블의 조건에 맞지 않는 데이터
SELECT 	d.DEPARTMENT_ID , l.LOCATION_ID 
FROM 	DEPARTMENTS d 
	INNER JOIN LOCATIONS l
	ON d.LOCATION_ID  = l.LOCATION_ID
WHERE d.DEPARTMENT_ID NOT IN (	SELECT DISTINCT e.DEPARTMENT_ID 
								FROM EMPLOYEES e
								inner join DEPARTMENTS d 
								ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
							)	
;

-- EMPLOYEES 테이블과 DEPARTMENTS 테이블의 조건에 맞는 데이터
SELECT 	d.DEPARTMENT_ID , l.LOCATION_ID 
FROM 	DEPARTMENTS d 
	INNER JOIN LOCATIONS l
	ON d.LOCATION_ID  = l.LOCATION_ID;
WHERE d.DEPARTMENT_ID  IN (	SELECT DISTINCT e.DEPARTMENT_ID 
								FROM EMPLOYEES e
								inner join DEPARTMENTS d 
								ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
							)	
;