--한줄주석
/*
	여러줄 주석
*/

-- employees 테이블에서 employee_id, last_name 출력

--SELECT * FROM tab;


--SELECT  employee_id, last_name
--FROM EMPLOYEES e 
--WHERE LAST_NAME = 'Smith'
--;

SELECT EMPLOYEE_ID, LAST_NAME 
FROM   EMPLOYEES e
WHERE  LAST_NAME ='Smith'
;

/*
 *  as : 별칭, 알리아스
 */
SELECT 	EMPLOYEE_ID AS "ID", 
		LAST_NAME 	AS "LName" 
FROM   	EMPLOYEES
WHERE  	LAST_NAME ='Smith'
;

SELECT 	EMPLOYEE_ID "ID", 
		LAST_NAME 	"LName",
		SALARY 		"SAL"
FROM   	EMPLOYEES
WHERE  	LAST_NAME ='Smith'
;

SELECT 	*
FROM 	EMPLOYEES
;

-- DISTINCT : 중복제거
SELECT	DISTINCT JOB_ID 
FROM 	EMPLOYEES e 
;

-- 부서 중복 제거 조회
SELECT 	DISTINCT  DEPARTMENT_ID 
FROM 	EMPLOYEES e 
;

-- >= , >, <=, <, =
-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- salary를 조회하는데 , salary 5000 이상인 사람의 정보를 조회
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME, 
		SALARY 
FROM 	EMPLOYEES e 
WHERE 	SALARY >= 5000
;

-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- salary를 조회하는데 , salary 5000 미만인 사람의 정보를 조회
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME, 
		SALARY 
FROM 	EMPLOYEES e 
WHERE 	SALARY = 4800
;

-- and
-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- department_id = 50이고 job_id = SH_CLERK 인 사람 조회
SELECT 	EMPLOYEE_ID, 
		FIRST_NAME ,
		LAST_NAME ,
		DEPARTMENT_ID,
		job_id
FROM 	EMPLOYEES e
WHERE 	DEPARTMENT_ID = 50
AND 	JOB_ID = 'SH_CLERK'
;

-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- job_id가 ST_MAN 이고, manager_id가 100이고
-- salary 5000이상인사람
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY 
FROM 	EMPLOYEES e
WHERE 	JOB_ID = 'ST_MAN'
AND 	MANAGER_ID = 100
AND		SALARY  >= 5000
;

-- or
-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- department_id = 50 또는 Manager_Id = 100
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	DEPARTMENT_ID  = 50
OR 		MANAGER_ID = 100
;

-- not, !=, <>
-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- DEPARTMENT_ID 50이 아닌 사람
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	NOT(DEPARTMENT_ID = 50)
;

-- !=
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	DEPARTMENT_ID != 50
;

-- <> = not
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	DEPARTMENT_ID <> 50
;

-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
-- Salary 4000 이상이고 8000이하인 50번 부서(DEPARTMENT_ID)가 아닌 사람
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	SALARY >= 4000
AND 	SALARY <= 8000
AND 	DEPARTMENT_ID <> 50
;

-- between A and B
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	SALARY BETWEEN 4000 AND 8000
AND 	DEPARTMENT_ID <> 50
;

-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name
--  SALARY 6500이고, 또는 7700이고, 또는 13000인 사람
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	SALARY = 6500
OR 		SALARY = 7700
OR 		SALARY = 13000
;

-- in
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES e
WHERE 	SALARY IN (6500, 7700, 13000)
;

SELECT * FROM EMPLOYEES e ;

-- EMPLOYEES 테이블에서 EMPLOYEE_ID, first_name, last_name, JOB_ID
-- MANAGER_ID, SALARY 를 조회
-- MANAGER_ID가 10 또는 30 또는 100 또는 90에 속하고,
-- 급여(SALARY)가 5000에서 10000사이 이고
-- 부서(MANAGER_ID)가 100이 아닌 사람을 조회
SELECT 	EMPLOYEE_ID ,
		FIRST_NAME ,
		LAST_NAME,
		JOB_ID ,
		MANAGER_ID ,
		SALARY ,
		DEPARTMENT_ID 
FROM 	EMPLOYEES 
WHERE 	MANAGER_ID IN  (10, 30, 90, 100)
AND		SALARY BETWEEN 5000 AND 10000
AND 	DEPARTMENT_ID <> 100
;

-- like(특정문자를 포함한 검색) : D로 시작하는 사람
SELECT 	FIRST_NAME ,
		LAST_NAME 
FROM 	EMPLOYEES e
WHERE 	FIRST_NAME LIKE 'D%'
;

-- like : e로 끝나는 사람
SELECT 	FIRST_NAME ,
		LAST_NAME 
FROM 	EMPLOYEES e
WHERE 	FIRST_NAME LIKE '%e'
;

-- like : 중간에 e가 들어가는 사람
SELECT 	FIRST_NAME ,
		LAST_NAME 
FROM 	EMPLOYEES e
WHERE 	FIRST_NAME LIKE '%e%'
;

SELECT 	FIRST_NAME ,
		LAST_NAME 
FROM 	EMPLOYEES e
WHERE 	FIRST_NAME LIKE '__a%'
;


-- is null
-- not commission
SELECT 	FIRST_NAME ,
		LAST_NAME ,
		COMMISSION_PCT 
FROM 	EMPLOYEES e 
WHERE 	COMMISSION_PCT IS NULL 
;

-- is not null
SELECT 	FIRST_NAME ,
		LAST_NAME ,
		COMMISSION_PCT 
FROM 	EMPLOYEES e 
WHERE 	COMMISSION_PCT IS NOT NULL 
;

-- 오름차순 ASC : ORDER BY [컬럼명] ASC
-- ASC 기본값, 생략가능
SELECT 	FIRST_NAME ,
		LAST_NAME ,
		COMMISSION_PCT 
FROM 	EMPLOYEES e 
WHERE 	COMMISSION_PCT IS NOT NULL 
ORDER BY COMMISSION_PCT ASC 
;


SELECT 	FIRST_NAME ,
		LAST_NAME ,
		COMMISSION_PCT 
FROM 	EMPLOYEES e 
WHERE 	COMMISSION_PCT IS NOT NULL 
ORDER BY COMMISSION_PCT , FIRST_NAME 
;